server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
        - id: tracker
          uri: lb://tracker
          predicates:
            - Path=/api/v1/transactions/**
        - id: authenticator
          uri: lb://authenticator
          predicates:
            - Path=/api/v1/auth/**
        - id: reporter
          uri: lb://reporter
          predicates:
            - Path=/api/v1/reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
