server:
  port: 8080

spring:
  application:
    name: tracker

  rabbitmq:
    username: ndkhoalk97
    password: 123456
    host: rabbitmq
    port: 5672

  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:postgres-tracker}:${RDS_PORT:5432}/${RDS_DB_NAME:transaction_tracker}
    username: ${RDS_USERNAME:ndkhoalk97}
    password: ${RDS_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  zipkin:
    base-url: http://zipkin:9411

rabbitmq:
  exchange:
    internal: internal.exchange
  routing-key:
    reporter: internal.reporter.routing.key
  queue:
    reporter: internal.reporter.queue

jwt:
  algorithm:
    secret: 123456 # Secret key used to sign the JWT token

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

grpc:
  server:
    report:
      host: reporter
      port: 9091




