server:
  port: 8081

spring:
  application:
    name: reporter
  rabbitmq:
    username: ndkhoalk97
    password: 123456
    host: rabbitmq
    port: 5672
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      database: reporter
      host: mongodb-reporter

  zipkin:
    base-url: http://zipkin:9411

rabbitmq:
  exchange:
    internal: internal.exchange
  routing-key:
    reporter: internal.reporter.routing.key
  queue:
    reporter: internal.reporter.queue

jwt:
  algorithm:
    secret: 123456 # Secret key used to sign the JWT token

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

