server:
  port: 8082

spring:
  application:
    name: reporter
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      database: reporter
      host: localhost
  zipkin:
    base-url: http://localhost:9411

jwt:
  algorithm:
    secret: 123456 # Secret key used to sign the JWT token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
